import type {
  TipoConfig,
  AnguloConfig,
  EstiloConfig,
  BlockFormat,
  HookBlockTypeConfig,
  AwarenessLevel,
  TrafficTemp,
  SubcomponentDef,
  HookFramework,
  TipoBloque,
  Brand,
  AIProviderConfig,
} from "@/types";

// ─── DESIGN TOKENS ────────────────────────────────────────────────────────────
export const T = {
  purple:      "#7A5AF6",
  purpleDark:  "#5B3FD4",
  purpleLight: "#BDC0EF",
  purpleBg:    "#F0EEFE",
  navy:        "#181349",
  navyMid:     "#252060",
  slate:       "#545F66",
  gray:        "#E4E6EA",
  grayLight:   "#F4F3FB",
  white:       "#FFFFFF",
  pain:        { color:"#D94F4F", bg:"#FFF2F2", border:"#F5BCBC" },
  promise:     { color:"#1A9E6E", bg:"#EDFAF4", border:"#9EE0C6" },
  proof:       { color:"#2878D4", bg:"#EEF5FF", border:"#A8CCFA" },
  constraints: { color:"#C07C10", bg:"#FFF8EA", border:"#F0D080" },
  curiosity:   { color:"#7A5AF6", bg:"#F0EEFE", border:"#BDC0EF" },
  conditions:  { color:"#C44F82", bg:"#FEF0F5", border:"#F0B4D0" },
  offer:       { color:"#0E7F8C", bg:"#EAFAFA", border:"#8ED8DE" },
  // ── Voltline-purple: canvas/superficie/elevación (mismo sistema, acento morado) ──
  canvas:        "#F1F0F8",
  surface:       "#FFFFFF",
  surfaceInset:  "#F4F3FB",
  borderSoft:    "#ECEEF3",
  green:         "#1A9E6E",
  greenBg:       "#EDFAF4",
  red:           "#D94F4F",
  redBg:         "#FFF2F2",
  radiusPill:    999,
  radiusCard:    18,
  radiusInput:   12,
  shadowCard:    "0 1px 2px rgba(24,19,73,0.05), 0 2px 8px rgba(24,19,73,0.05), 0 1px 0 rgba(24,19,73,0.04)",
  shadowHover:   "0 10px 24px rgba(24,19,73,0.1), 0 2px 6px rgba(24,19,73,0.06)",
  shadowAccent:  "0 0 0 1px rgba(122,90,246,0.35), 0 10px 26px rgba(122,90,246,0.25)",
  shadowModal:   "0 32px 70px rgba(15,10,50,0.28), 0 10px 24px rgba(15,10,50,0.12), 0 0 0 1px rgba(122,90,246,0.06)",
};

export const font = `'Inter', 'Helvetica Neue', sans-serif`;
export const fontDisplay = `'Space Grotesk', 'Inter', sans-serif`;
export const fontMono = `'JetBrains Mono', 'SF Mono', Menlo, monospace`;

// ─── CONSTANTS ────────────────────────────────────────────────────────────────
export const TIPOS: TipoConfig[] = [
  { id:"pain",        label:"Dolor",       ...T.pain },
  { id:"promise",     label:"Promesa",     ...T.promise },
  { id:"proof",       label:"Prueba",      ...T.proof },
  { id:"constraints", label:"Frenos",      ...T.constraints },
  { id:"curiosity",   label:"Curiosidad",  ...T.curiosity },
  { id:"conditions",  label:"Condiciones", ...T.conditions },
  { id:"offer",       label:"Oferta",      ...T.offer },
];

export const FUNCIONES: string[] = ["hook","body","headline","cta","offer"];
export const FL: Record<string, string> = { hook:"Hook", body:"Body", headline:"Headline", cta:"CTA", offer:"Offer" };
export const FC: Record<string, string> = { hook:T.purple, body:T.slate, headline:T.proof.color, cta:T.conditions.color, offer:T.offer.color };

export const ANGULOS: AnguloConfig[] = [
  { id:"contrarian",    label:"Contraintuitivo",
    desc:"Contradice algo que todos dan por sentado. Crea disonancia cognitiva inmediata.",
    example:"Stopping saved audiences was the best thing I did for my campaigns.",
    adExample:"Dejé de usar audiencias guardadas y mis costos bajaron un 40%.\n\nTodos los expertos dicen que son esenciales.\nYo digo que estaban destruyendo mi ROAS.\n\nAquí exactamente qué hice en cambio →" },
  { id:"whistleblower", label:"Denunciante",
    desc:"Expone una verdad incómoda que la industria no quiere que sepas.",
    example:"The real reason your agency isn't showing you the full picture.",
    adExample:"La razón real por la que tu agencia no te muestra el costo por resultado.\n\nNo es incompetencia. Es un incentivo.\n\nTe explico cómo leer las métricas que de verdad importan →" },
  { id:"story",         label:"Historia",
    desc:"Momento específico en el tiempo. El cerebro necesita saber qué pasó — vívido, tiempo presente.",
    example:"6 months ago my business spent $2k/month with zero results.",
    adExample:"Hace 6 meses gastaba Bs. 800 al mes en ads sin ver un solo domicilio nuevo.\n\nHoy tenemos 47 pedidos diarios.\n\nLa diferencia no fue el presupuesto — fue saber exactamente qué medir." },
  { id:"howto",         label:"Cómo hacerlo",
    desc:"Enseña algo específico y accionable. Autoridad por demostración — muestra el método.",
    example:"How to cut your CPL in half without changing your budget.",
    adExample:"Cómo conseguir domicilios a Bs. 8 sin subir el presupuesto.\n\n3 cambios en tu campaña de Meta Ads:\n✓ Cambiar el objetivo de campaña\n✓ Ajustar la ventana de atribución\n✓ Reemplazar el hook del anuncio\n\nCosto por pedido cayó de Bs. 22 a Bs. 8 en 11 días." },
  { id:"comparison",    label:"Comparación",
    desc:"Nosotros vs ellos, método viejo vs nuevo, antes vs después. El contraste crea claridad.",
    example:"Most agencies take 90 days to show results. We show them in 7.",
    adExample:"La mayoría de dueños de restaurante espera 3 meses para ver resultados en ads.\nNosotros los vemos en 7 días.\n\nNo es magia — es saber qué indicadores seguir desde el día 1.\n\nTe mostramos cómo →" },
  { id:"confession",    label:"Confesión",
    desc:"El experto admite algo inesperado o vergonzoso. Alta credibilidad por la vulnerabilidad.",
    example:"I spent $8,000 on Meta Ads before understanding why it wasn't working.",
    adExample:"Gasté $8,000 en Meta Ads antes de entender por qué nada funcionaba.\n\nEl error era tan obvio que me da vergüenza.\n\nHoy enseño a mis alumnos exactamente lo que aprendí — para que no pasen por lo mismo." },
  { id:"dayinlife",     label:"Un día en mi vida",
    desc:"Documenta tu proceso real o la transformación de un cliente. 'Documenta, no crees' — Garyvee.",
    example:"What my Monday looks like managing $200k/month in ad spend.",
    adExample:"Lunes 7am. Abro Ads Manager.\n3 campañas activas. ROAS: 4.2x, 3.8x, y una que pausaré hoy.\n\nAsí empieza mi semana gestionando ads para restaurantes locales en Bolivia.\nDocumento todo para que puedas hacer lo mismo." },
  { id:"analyzer",      label:"Analizador",
    desc:"Estudiaste algo externo y compartes los patrones. No necesitas ser experto — solo observador.",
    example:"I analysed 50 ads that spent over $100k. They all had one thing in common.",
    adExample:"Analicé los 50 ads de restaurantes en Bolivia que más gastaron el año pasado.\n\nEl 94% tenía algo en común.\nEl 89% de los que no funcionaron también — pero diferente.\n\nTe explico ambas cosas." },
  { id:"fear",          label:"Miedo / Consecuencias",
    desc:"Qué pasa si NO actúan — consecuencias específicas, vívidas, que se acumulan con el tiempo.",
    example:"Every day you delay is another day your competitor takes your customers.",
    adExample:"Cada semana sin domicilios propios = Bs. 500 que van a la app de delivery.\n\nY el 30% de comisión que pagas no te deja a ti los clientes — te los deja a ellos.\n\n¿Cuándo fue la última vez que un cliente de PedidosYa volvió y te pidió directo?" },
  { id:"aspiration",    label:"Aspiración",
    desc:"Pinta la transformación a nivel identidad que tu avatar quiere. No características — su yo futuro.",
    example:"What life looks like when your ads print money while you sleep.",
    adExample:"Imagina abrir Ads Manager el lunes y ver 23 pedidos llegaron mientras dormías.\n\nSin llamadas. Sin coordinar.\nSolo pedidos listos para entregar.\n\nEso es lo que pasa cuando tienes el sistema correcto." },
  { id:"socialproof",   label:"Prueba social",
    desc:"Lidera con resultados que otros han logrado. Deja que los números y nombres hablen.",
    example:"300 students. Average 3x ROAS improvement in the first 30 days.",
    adExample:"Restaurante Don Beto: 3 domicilios diarios en enero. 47 en marzo.\n\nUn solo cambio en su estrategia de Meta Ads.\nMisma zona. Mismo presupuesto. Diferente sistema." },
  { id:"mythbusting",   label:"Desmitificador",
    desc:"Destruye una creencia común que tiene tu avatar y lo frena de encontrar la solución correcta.",
    example:"More budget doesn't mean better results. Here's what actually does.",
    adExample:"El error: creer que más presupuesto = más clientes.\n\nLa realidad: el 80% de restaurantes que conozco gasta de más en las audiencias equivocadas.\n\nEl presupuesto no es el problema. El sistema sí." },
  { id:"challenge",     label:"Desafío",
    desc:"Call-out directo o reto. Alto engagement, polarizante — filtra a la audiencia correcta.",
    example:"If you can't answer these 3 questions about your campaigns, we need to talk.",
    adExample:"3 preguntas que todo dueño de restaurante debería responder antes de gastar en ads:\n\n1. ¿Cuánto te cuesta conseguir un cliente nuevo?\n2. ¿Cuánto vale ese cliente en 6 meses?\n3. ¿Qué % de tus clientes repiten?\n\nSi no sabes las 3, hay algo importante que resolver primero." },
];

export const ESTILOS: EstiloConfig[] = [
  { id:"ugc",         label:"UGC",              desc:"Estilo generado por el usuario. Crudo, auténtico, filmado con celular.", example:"Cámara temblorosa, luz natural, hablando directo a cámara como un amigo." },
  { id:"talkinghead", label:"Talking head",     desc:"Limpio, directo a cámara. Profesional pero personal.", example:"Persona habla a cámara, fondo simple, audio claro." },
  { id:"founderfled", label:"Fundador a cámara",desc:"El fundador cuenta la historia. Autoridad + autenticidad combinadas.", example:"'Empecé esto porque estaba frustrado con…'" },
  { id:"testimonial", label:"Testimonio",       desc:"Cliente real comparte su resultado. Mejor con números específicos.", example:"'En 30 días pasé de ROAS 1.2x a 3.8x usando este método.'" },
  { id:"voiceover",   label:"Voz en off + B-roll",desc:"Narración sobre imágenes relevantes. Cinematográfico, escalable.", example:"Voz o texto sobre tomas del producto, footage de clientes, o screen recordings." },
  { id:"textonscreen",label:"Texto en pantalla", desc:"Subtítulos en negrita llevan el mensaje. Funciona sin sonido.", example:"Texto superpuesto a ritmo rápido sincronizado con música." },
  { id:"documentary", label:"Documental",       desc:"Basado en historia, multi-toma. Detrás de cámaras o recorrido del cliente.", example:"Seguir a un cliente a través de su transformación en el tiempo." },
  { id:"beforeafter", label:"Antes y después",  desc:"Contraste visual. Muestra la transformación claramente.", example:"Pantalla dividida o tomas secuenciales mostrando el cambio claro." },
  { id:"tutorial",    label:"Tutorial",         desc:"Enseña algo útil. Valor primero, CTA al final.", example:"'Aquí exactamente cómo configuro mi campaña de Meta en 10 minutos.'" },
  { id:"skit",        label:"Sketch / comedia", desc:"Humor y identificación. Alta viralidad.", example:"Dramatiza el problema o el contraste de forma graciosa y exagerada." },
];

// ─── BLOCK FORMATS ────────────────────────────────────────────────────────────
export const CUSTOM_FORMAT: BlockFormat = { id:"custom", label:"✏️ Formato personalizado…" };

export const BLOCK_FORMATS: Record<string, BlockFormat[]> = {
  hook: [
    { id:"pain_curiosity",   cat:"Estructura",          label:"Dolor + Curiosidad",              hint:"Nombra el dolor exacto y añade un mecanismo que genera intriga. '¿Por qué [problema] (y cómo [mecanismo] lo resuelve)?'", ej:"por qué tu cocina de 15 años te sigue costando plata (y cómo el Plan Precio Cerrado lo resuelve sin que tengas que coordinar nada)" },
    { id:"promise_curiosity",cat:"Estructura",          label:"Promesa + Curiosidad",             hint:"Promete un resultado ligado a algo contraintuitivo. 'Cómo [resultado] haciendo solo [mecanismo inesperado]'", ej:"cómo tener tu cocina nueva en 3 semanas exactas — sin coordinar gremios, sin que te cobren extras a mitad de obra, sin irte de tu casa" },
    { id:"contrarian",       cat:"Estructura",          label:"Contraintuitivo",                  hint:"Contradice algo que todos dan por sentado. '[Lo que todos hacen] está destruyendo tu [X]. Por qué.'", ej:"el presupuesto más barato es casi siempre el más caro al final — y todos en el rubro lo saben antes de enviártelo" },
    { id:"stakes",           cat:"Estructura",          label:"Consecuencias / Stakes",           hint:"Muestra qué pasa si NO actúan. 'Cada [período] sin [acción] = [consecuencia que se acumula]'", ej:"cada mes que postergás la remodelación, los materiales suben de precio — la misma cocina que hoy vale $4.900 el año que viene puede costarte $5.800" },
    { id:"teacher",          cat:"Posicionamiento",     label:"Maestro (experto)",                hint:"Enseña algo específico desde experiencia propia. 'Las [N] cosas que siempre hago para [resultado]'", ej:"las 3 preguntas que hago antes de firmar cualquier contrato de remodelación para que no me sumen extras a mitad de obra" },
    { id:"analyzer",         cat:"Posicionamiento",     label:"Analizador",                       hint:"Sintetiza algo que estudiaste externamente. 'Analicé [N] [cosas]. Esto tienen en común los que funcionaron.'", ej:"revisé 50 remodelaciones que se salieron de presupuesto. Todas tenían lo mismo: cotización sin partidas cerradas y sin penalidad por atraso" },
    { id:"journey",          cat:"Posicionamiento",     label:"Documentando el camino",           hint:"Documenta tu proceso en tiempo real. 'Día/Semana [N] de [proceso]. Esto pasó.'", ej:"semana 1 de remodelar nuestra cocina. Esto es lo que nadie te cuenta antes de empezar — y lo que nosotros hacemos diferente" },
    { id:"confessional",     cat:"Posicionamiento",     label:"Confesión",                        hint:"Admite algo inesperado o incómodo. 'Gasté [cantidad] en [cosa] antes de entender [verdad].'", ej:"gasté $2.000 en 'extras' que nadie me avisó antes de entender que sin precio cerrado en el contrato, siempre terminás pagando de más" },
    { id:"cant_believe",     cat:"Plantillas probadas", label:"No puedo creer que existe esto",   hint:"FOMO inmediato. 'No puedo creer que [descubrimiento valioso] esté [disponible/funcionando así]'", ej:"no puedo creer que sea posible remodelar tu cocina completa en 3 semanas con precio cerrado, diseño 3D gratis y garantía de 5 años" },
    { id:"controversial",    cat:"Plantillas probadas", label:"Esto puede ser controversial…",    hint:"Abre un bucle de tensión. Polariza. 'Esto puede ser controversial: [verdad que genera fricción]'", ej:"esto puede sonar controversial: pedir 5 presupuestos no te protege de los sobrecostos si ninguno cierra el precio por contrato" },
    { id:"never_again",      cat:"Plantillas probadas", label:"Por qué nunca volvería a X",       hint:"Confesional + contraintuitivo. 'Por qué nunca volvería a [práctica común] después de [descubrimiento]'", ej:"por qué nunca volvería a contratar una remodelación sin pedir precio y fecha cerrados primero (estuve 11 semanas con la cocina sin funcionar)" },
    { id:"illegal",          cat:"Plantillas probadas", label:"Se siente ilegal de saber",        hint:"Acceso privilegiado. VARÍA el inicio — nunca repitas la misma frase: 'Nadie te va a contar esto:', 'Si los del gremio me escuchan, me odian.', 'El dato que todos esconden:', 'Lo que callamos en la industria:', 'Llevo años sabiendo esto y nunca lo dije.' El insight en sí debe ser específico al negocio.", ej:"lo que nadie en el rubro te dice: el precio 'barato' de la cotización inicial raramente es el precio final — y lo saben antes de enviártelo" },
    { id:"unpopular",        cat:"Plantillas probadas", label:"Opinión impopular",                hint:"Postura firme contra algo ampliamente aceptado. 'Opinión impopular: [creencia contraria a tu mercado]'", ej:"opinión impopular: la mayoría de remodelaciones se atrasa porque el cliente no exigió fecha en el contrato, no porque el maestro sea malo" },
    { id:"kept_for_me",      cat:"Plantillas probadas", label:"Lo iba a guardar para mí pero…",  hint:"Exclusividad. 'Lo iba a guardar para mí, pero [insight, estrategia, o recurso valioso]'", ej:"lo iba a guardar para mí pero: la razón por la que el 94% de nuestras obras se entrega en la fecha pactada es una sola cosa que casi nadie en el rubro hace" },
    { id:"stop_doing",       cat:"Plantillas probadas", label:"Para de hacer X",                  hint:"Interrumpe un comportamiento contraproducente. 'Para de [acción dañina] antes de [condición previa]'", ej:"para de pedir más presupuestos si ninguno te da precio cerrado por contrato — solo vas a confirmar que el más barato te va a salir el más caro" },
    { id:"real_result",      cat:"Plantillas probadas", label:"Resultado de alguien real",        hint:"La más creíble. 'Cómo [persona específica] logró [resultado con número] en [tiempo] con [mecanismo]'", ej:"la familia Áñez tenía una cocina de 15 años, muebles hinchados y dos maestros que los dejaron a mitad de obra. La dejamos nueva en 18 días, dentro del precio de contrato." },
    { id:"enthusiasm",       cat:"Emoción",             label:"Entusiasmo personal",               hint:"'Acabo de conseguir [X] y estoy súper emocionado/a.' Energía genuina que contagia." },
    { id:"myth_reveal",      cat:"Emoción",             label:"Mito revelado",                     hint:"'[N] mitos sobre [X] que te están costando plata.' Destruye creencias falsas del avatar." },
    { id:"frustration_hook", cat:"Emoción",             label:"Frustración cotidiana",             hint:"'[Situación frustrante] es una lucha constante.' El avatar siente que alguien por fin lo entiende." },
    { id:"obsession",        cat:"Emoción",             label:"Obsesión / Adicción positiva",      hint:"'Estoy completamente obsesionado/a con [X].' Genera FOMO y curiosidad inmediata." },
    { id:"age_identity",     cat:"Emoción",             label:"Identidad por edad o grupo",        hint:"'Tengo [edad/rol]. Así es cómo [X] me ayudó con [problema].' Identificación inmediata con el avatar." },
    { id:"honest_review",    cat:"Emoción",             label:"Opinión honesta",                   hint:"'Mi opinión honesta sobre [X] después de [tiempo].' Alta credibilidad por transparencia percibida." },
    { id:"tutorial_steps",   cat:"Paso a paso", label:"X pasos para [resultado]",      hint:"'[N] pasos para [resultado específico con número].' Enuncia el resultado primero, muestra los pasos, implica la simplicidad." },
    { id:"howto_journey",    cat:"Paso a paso", label:"Cómo fui de A a B en [tiempo]", hint:"'Cómo fui de [situación mala] a [resultado] en solo [tiempo].' Proceso concreto, tiempo específico." },
    { id:"formula_steps",    cat:"Paso a paso", label:"La fórmula de [X]",             hint:"'La [NOMBRE DE FÓRMULA]: [resultado] en [poco tiempo].' Dale un nombre memorable al proceso." },
    { id:"authority_steal",  cat:"Autoridad",   label:"Roba mi estrategia exacta",     hint:"'Roba mi estrategia exacta para [resultado].' Implica que el oyente obtiene algo probado y funcional." },
    { id:"authority_years",  cat:"Autoridad",   label:"Pasé X años dominando esto",    hint:"'Pasé [N] años dominando [tema], pero puedo simplificarlo en [tiempo corto].' Experiencia + accesibilidad." },
    { id:"authority_helped", cat:"Autoridad",   label:"[N] personas lograron [X]",     hint:"'Esta estrategia ayudó a [N] de mis [clientes/alumnos] a lograr [resultado].' Prueba de escala." },
    { id:"before_after",     cat:"Transformación", label:"De [malo] a [bueno] en [tiempo]",  hint:"'De [situación mala] a [situación buena] en [tiempo].' Sin contexto extra — el contraste habla solo." },
    { id:"before_after_date",cat:"Transformación", label:"Hace X meses: [dolor]. Hoy: [ganancia].", hint:"Usa líneas separadas. 'Hace 6 meses: [dolor vivido]. Hoy: [ganancia con número].' Visual y específico." },
    { id:"direct_question",  cat:"Pregunta directa", label:"¿Alguna vez has [frustración]?", hint:"'¿Alguna vez te preguntaste por qué [punto de dolor]? Aquí está la razón real.' Reconocimiento inmediato." },
    { id:"comparison_gap",   cat:"Comparación", label:"La diferencia entre promedio y excepcional", hint:"'La diferencia entre [resultado promedio] y [resultado excepcional] es solo una cosa. Aquí está:'" },
    { id:"trend_change",     cat:"Tendencia",   label:"[X] está cambiando en [año]",   hint:"'[Plataforma/industria] está cambiando en [año] — y esto significa [impacto concreto para el avatar].'" },
    { id:"fear_costing",     cat:"Advertencia", label:"Este error te está costando [X]",hint:"'Este simple error podría estar costándote [dinero/tiempo/clientes].' Amenaza específica, no genérica." },
    { id:"fear_warning",     cat:"Advertencia", label:"Para de hacer X antes de que empeore", hint:"'Para de [acción dañina] ahora, antes de [consecuencia que se acumula].' Urgencia concreta." },
    CUSTOM_FORMAT,
  ],
  pain: [
    { id:"d1_costo_invisible", label:"Costo invisible",        hint:"Cada ciclo que sigue {Avatar.antes}, una pérdida concreta que no estaban calculando. Requiere {Avatar.antes} cuantificado; sin número, placeholder [agregar costo real]. Nunca abstracto.", ej:"Cada año que postergás, la humedad sigue dañando tus muebles — y reemplazarlos después te sale más caro que renovarlos hoy." },
    { id:"d2_nicho",           label:"Dolor del nicho",        hint:"Habla EXACTO como el cliente ({Avatar.rol} + {Avatar.vocabulario}). Cuanto más específico el rol, más alto el hook rate.", ej:"¿Tu cocina tiene más de 10 años, muebles hinchados y te da vergüenza cuando llega visita?" },
    { id:"d3_trampa_esfuerzo", label:"Trampa del esfuerzo",    hint:"Valida el esfuerzo ({Avatar.solucion_fallida}) y aún así {Avatar.dolor}. Nunca culpes al prospecto — el problema está antes de lo que ve.", ej:"Pintaste, cambiaste la grifería, ordenaste los cajones… y la cocina sigue viéndose vieja. El problema no es lo que le sumas." },
    { id:"d4_acumula",         label:"Problema que se acumula",hint:"Funciona a escala chica; al crecer las costuras se ven. Tono descriptivo, no acusatorio.", ej:"Primero fue un cajón tuyo que no cerraba. Después el mesón manchado. Ahora tu cocina entera te pide que actúes." },
    { id:"d5_frustracion",     label:"Frustración cotidiana",  hint:"Lo que pasa cada ciclo en las palabras del cliente ({Avatar.vocabulario}), no la crisis total.", ej:"¿Ese momento de cocinar peleando con cajones que no abren y sin dónde apoyar nada?" },
    { id:"d6_diagnostico",     label:"Diagnóstico inesperado", hint:"'No es {Avatar.creencia_falsa}, es {Mecanismo.creencia_rebate}.' Requiere Mecanismo; sin él no afirmes la causa real.", ej:"Tu cocina no se ve vieja por los muebles. Se ve vieja por la luz y la distribución — y eso es lo que casi nadie corrige." },
    { id:"a3_stakes",          label:"Consecuencias de no actuar", hint:"Cada ciclo de inacción = costo acumulable calculable. Un número específico vende 10× más. Sin {Oferta.restriccion}, no fabriques urgencia.", ej:"Cada temporada que esperas, el costo de los materiales sube — y la misma cocina te cuesta más que el año pasado." },
    CUSTOM_FORMAT,
  ],
  promise: [
    { id:"p1_x_a_y",         label:"De X a Y en tiempo",         hint:"'De {Oferta.antes} a {Oferta.despues} en {Oferta.tiempo}.' Sin antes+después, deshabilitar; sin caso real es promesa, no testimonio.", ej:"De tu cocina de 15 años — muebles hinchados, mesón manchado — a una cocina nueva y lista para usar en solo 3 semanas." },
    { id:"p2_sin_sacrificio",label:"Sin el sacrificio esperado", hint:"'{Oferta.resultado} sin {Avatar.objection}.' No apiles objeciones — 1 o 2 máximo, o suena imposible.", ej:"Renueva tu cocina sin sobrecostos a mitad de obra y sin tener que mudarte de tu casa." },
    { id:"benefits",         label:"Lista de beneficios",        hint:"Cada beneficio sale de {Oferta.items}: número concreto, no adjetivo. No inventes características que no estén en la oferta.", ej:"✓ Diseño 3D gratis ✓ Precio cerrado por contrato ✓ Lista en 3 semanas ✓ Garantía de 5 años" },
    { id:"future_pace",      label:"Futuro visualizado",         hint:"Lleva al lector a vivir {Oferta.despues} como si ya lo tuviera. Activa la identidad futura.", ej:"Imagina entrar el sábado a una cocina amplia, con buena luz e isla nueva — y recibir a tus visitas sin pena." },
    { id:"identity",         label:"Transformación de identidad",hint:"Nueva identidad, no solo un resultado. Usa {Avatar.deseo}.", ej:"Deja de disculparte por tu cocina. Conviértela en la mejor parte de tu casa." },
    { id:"bab",              label:"Antes / Después",            hint:"Antes: {Oferta.antes} con número. Después: {Oferta.despues} con número. Puente: qué cambió ({Mecanismo}).", ej:"Antes: tus muebles hinchados, el mesón manchado, la cocina que te da vergüenza. Después: cocina moderna en 18 días, precio que no se movió. El cambio: un solo equipo y precio cerrado por contrato." },
    CUSTOM_FORMAT,
  ],
  proof: [
    { id:"pr1_n_usuarios", label:"Número de clientes",        hint:"'{Prueba.n_clientes} {tipo de cliente} ya {resultado}.' Número NO redondo, tal cual el cerebro. Sin {Prueba.n_clientes}: deshabilitar.", ej:"+180 cocinas remodeladas en Santa Cruz desde 2019." },
    { id:"pr2_caso_real",  label:"Resultado de cliente real", hint:"{Prueba.caso}: perfil + resultado + tiempo (los tres). Sin caso real: deshabilitar — jamás inventar clientes ni números.", ej:"La familia Áñez en Equipetrol renovó su cocina de 12 m² en 18 días, dentro del precio de contrato." },
    { id:"pr3_autoridad",  label:"Autoridad externa",         hint:"Cita o reconocimiento de {Prueba.autoridad} real. 'Según expertos' NO es autoridad. Sin dato verificable: deshabilitar.", ej:"Instaladores certificados de encimeras de cuarzo Silestone." },
    { id:"pr4_cuota",      label:"Cuota de mercado",          hint:"'{Prueba.cuota_mercado}' (X de cada Y en [mercado]). Dato real; sin él, deshabilitar.", ej:"1 de cada 4 remodelaciones de cocina en la zona norte las hacemos nosotros." },
    { id:"b1_maestro",     label:"Autoridad demostrada",      hint:"'Trabajé con {Prueba.n_clientes}; el patrón era {Mecanismo.diferenciador}.' Demuestra con número, no declares 'soy experto'.", ej:"Remodelamos 180 cocinas y el patrón es claro: el 94% se entrega en la fecha pactada gracias al precio cerrado." },
    { id:"b2_analizador",  label:"Analizador",                hint:"'Analicé {Prueba.n_clientes} {objeto}. Esto encontré: {hallazgo}.' Sin dato real usa 'en los casos que vi', nunca inventes el N.", ej:"Revisamos 50 remodelaciones que se salieron de presupuesto. Todas tenían algo en común: cotización sin partidas cerradas." },
    CUSTOM_FORMAT,
  ],
  curiosity: [
    { id:"c1_causa",    label:"La causa inesperada",    hint:"'La razón de {Avatar.dolor} no es {Avatar.creencia_falsa}. Es {Mecanismo.creencia_rebate}' (insinuado, no explicado del todo).", ej:"La razón por la que tu cocina se ve vieja no son los muebles. Es la distribución y la luz." },
    { id:"c2_secreto",  label:"Secreto del nicho",      hint:"'Lo que {industria/competidores} no te dicen: {Mecanismo.diferenciador}.' Refuerza con {Prueba.autoridad} si existe.", ej:"Lo que los maestros no te dicen: el 'precio barato' del inicio casi nunca es el precio final." },
    { id:"mechanism",   label:"Mecanismo insinuado",    hint:"'{Oferta.resultado}. No con {lo que todos asumen}. Con {Mecanismo.nombre}.' Si NO hay Mecanismo.nombre, no inventes uno: usa 'un sistema/un método'.", ej:"Cocina nueva en 3 semanas con precio que no se mueve. No con suerte. Con el Plan Precio Cerrado." },
    { id:"open_loop",   label:"Pregunta sin respuesta", hint:"Abre un bucle con {Avatar.dolor} y no lo cierres — el lector NECESITA seguir para resolverlo.", ej:"Hay una sola razón por la que la mayoría de remodelaciones se atrasa — y se puede evitar desde el contrato." },
    { id:"c5_dato",     label:"Dato contraintuitivo",   hint:"Un dato sorprendente y REAL de {Prueba}. Sin dato real: deshabilitar — no inventes estadísticas.", ej:"El 94% de nuestras obras se entrega en la fecha pactada o antes. En el rubro, eso casi no pasa." },
    CUSTOM_FORMAT,
  ],
  cta: [
    { id:"direct",     label:"Acción directa",          hint:"Di exactamente qué hacer + el resultado inmediato.", ej:"Agenda tu visita y diseño 3D gratis. En la primera reunión te damos el precio cerrado." },
    { id:"low_risk",   label:"Sin fricción",            hint:"'{Acción}. {Oferta.friccion_eliminada}.' Borra la razón para no actuar: sin anticipo, sin compromiso.", ej:"Pide tu diseño 3D gratis. Sin anticipo hasta que firmes el plan." },
    { id:"benefit",    label:"Beneficio + acción",      hint:"Resultado primero: 'Consigue {Oferta.resultado} — {acción}.'", ej:"Ten la cocina que siempre quisiste, con fecha y precio garantizados. Agenda tu visita." },
    { id:"urgency",    label:"Urgencia real",           hint:"Solo con {Oferta.restriccion} REAL (cupos/fecha). Sin restricción real, no fabriques urgencia — usa otro CTA.", ej:"Solo tomamos 6 obras al mes. Quedan 2 cupos para este mes — agenda tu visita." },
    { id:"callout",    label:"Si cumples, actúa",       hint:"'Si {Avatar.situacion calificadora}, {acción} + {qué pasa después}.' Filtra y califica.", ej:"Si tu cocina tiene más de 10 años y vives en zona norte, escríbenos: te damos diseño 3D gratis." },
    { id:"social_cta", label:"Únete a los demás",       hint:"'{Prueba.n_clientes} ya {resultado}. Sumá el tuyo.' Requiere {Prueba.n_clientes} real.", ej:"+180 familias ya tienen su cocina nueva. Agenda tu visita gratis y suma la tuya." },
    CUSTOM_FORMAT,
  ],
  constraints: [
    { id:"co1_mito",        label:"Mito derribado",            hint:"'{Avatar.creencia_falsa} no es lo que frena tus resultados. Es {Mecanismo.creencia_rebate}.' Requiere Mecanismo; sin él, deshabilitar.", ej:"Remodelar tu cocina no tiene que significar meses de obra y polvo por toda tu casa. Con precio y fecha cerrados en el contrato son 3 semanas y un solo frente de trabajo." },
    { id:"co2_paradoja",    label:"Paradoja del esfuerzo",     hint:"'{Avatar.solucion_fallida}' bien hecho no alcanza sin {Mecanismo.descripcion}. El esfuerzo no es el problema.", ej:"Puedes pedir 5 presupuestos más, pero si ninguno cierra precio por contrato, vas a terminar pagando 'extras' igual." },
    { id:"co4_no_necesitas",label:"No necesitas",              hint:"'No necesitás {Avatar.objection / el prerrequisito que asumen}.' Derriba la barrera de entrada.", ej:"No necesitas contratar arquitecto, maestro y mueblería por separado. Nosotros somos un solo equipo." },
    { id:"direct_obj",      label:"Respuesta a objeción",      hint:"Nombra {Avatar.objection} y respóndela con evidencia ({Prueba}). El 'Sí, pero…' resuelto.", ej:"'¿Y si se atrasan?' Si pasa la fecha del contrato, la penalidad la pagamos nosotros." },
    { id:"belief",          label:"Creencia limitante",        hint:"Las creencias son maleables: prueba + reencuadre.", ej:"Creías que una cocina linda cuesta una fortuna. Con precio cerrado y financiamiento a 12 meses, es más alcanzable de lo que piensas." },
    { id:"money",           label:"Costo de no actuar",        hint:"Costo de NO actuar vs costo de actuar, con números reales de {Oferta} y {Avatar.antes}.", ej:"Cada año que postergás, los materiales suben de precio. La misma cocina que hoy vale $4.900 el año que viene puede costarte $5.800 — y habrás aguantado 12 meses más en la cocina que te da vergüenza." },
    CUSTOM_FORMAT,
  ],
  conditions: [
    { id:"cn1_si_entonces",     label:"Si/Entonces",          hint:"'Si {Avatar.situacion específica}, {consecuencia o resultado posible}.' Califica al prospecto correcto.", ej:"Si tu cocina ya tiene muebles hinchados, cada mes que esperas el daño avanza al resto." },
    { id:"cn2_callout_rol",     label:"Callout de rol",       hint:"'{Avatar.rol} en {Marca.mercado}: …' Filtra a la audiencia exacta de inmediato.", ej:"¿Dueño de casa en la zona norte de Santa Cruz? Esto es para ti." },
    { id:"cn6_callout_problema",label:"Callout por problema", hint:"Llama al avatar por {Avatar.dolor} específico.", ej:"Si te da vergüenza tu cocina cuando llega visita, agenda una visita esta semana." },
    { id:"cn5_cupos",           label:"Escasez de cupos",     hint:"{Oferta.restriccion} real con número ('solo 20 cupos'). Sin restricción real: deshabilitar — la escasez falsa destruye confianza.", ej:"Solo tomamos 6 obras al mes para cumplir el plazo. Quedan 2 cupos este mes." },
    { id:"cn7_deadline",        label:"Deadline real",        hint:"Fecha concreta de {Oferta.restriccion}. 'Hasta el viernes 6' > 'por tiempo limitado'. Sin fecha real: deshabilitar.", ej:"El diseño 3D gratis va solo hasta fin de mes. Después vuelve a costar $150." },
    CUSTOM_FORMAT,
  ],
  offer: [
    { id:"of1_stack",   label:"Stack de valor con ancla",  hint:"Lista {Oferta.items} (nombre + beneficio + valor). Compara {Oferta.precio_ancla} vs {Oferta.precio}. Sin items con valor: deshabilitar.", ej:"Incluye: diseño 3D ($150) + muebles a medida + mesón de cuarzo + instalación. Por separado: $8.000. Todo junto: desde $4.900." },
    { id:"of2_gratis",  label:"Acceso gratuito",           hint:"'{Oferta.resultado}. {Oferta.friccion_eliminada}.' Especifica cómo, cuánto tiempo, sin anticipo — los detalles convierten.", ej:"Diseño 3D de tu cocina nueva, gratis. Sin anticipo hasta que firmes el plan." },
    { id:"of4_garantia",label:"Garantía",                  hint:"{Oferta.garantia} completa: condición + plazo + cómo funciona. Sin garantía real: deshabilitar.", ej:"Garantía de 5 años. Y si nos atrasamos del plazo del contrato, la penalidad la pagamos nosotros." },
    { id:"of3_descuento",label:"Descuento con contexto",   hint:"{Oferta.precio} + la razón REAL del descuento. Sin razón genuina: omítelo, no fabriques urgencia.", ej:"Por apertura de temporada: el diseño 3D ($150) va gratis para las primeras 6 cocinas del mes." },
    { id:"of7_tiempo",  label:"Tiempo limitado real",      hint:"{Oferta.restriccion} genuina (fecha/cupos/razón). Sin restricción real: deshabilitar.", ej:"Precio cerrado garantizado si firmas este mes. Después se ajusta al nuevo costo de materiales." },
    CUSTOM_FORMAT,
  ],
};

// ─── HOOK BLOCK TYPES ─────────────────────────────────────────────────────────
export const HOOK_BLOCK_TYPES: HookBlockTypeConfig[] = [
  { id:"pain",        label:"Dolor",       emoji:"💔", color:T.pain.color,        bg:T.pain.bg,        desc:"Lidera con la lucha del avatar — se reconocen inmediatamente." },
  { id:"promise",     label:"Promesa",     emoji:"✨", color:T.promise.color,     bg:T.promise.bg,     desc:"Lidera con la transformación o resultado — los atrae hacia el futuro que quieren." },
  { id:"proof",       label:"Prueba",      emoji:"⭐", color:T.proof.color,       bg:T.proof.bg,       desc:"Lidera con un resultado real o testimonio — credibilidad instantánea detiene el scroll." },
  { id:"curiosity",   label:"Curiosidad",  emoji:"🔮", color:T.curiosity.color,   bg:T.curiosity.bg,   desc:"Insinúa el mecanismo — crea un bucle abierto que necesitan resolver." },
  { id:"contrarian",  label:"Contrarian",  emoji:"⚡", color:T.constraints.color, bg:T.constraints.bg, desc:"Desafía una creencia ampliamente aceptada — la disonancia cognitiva congela el pulgar." },
  { id:"offer",       label:"Oferta",      emoji:"🎁", color:T.offer.color,       bg:T.offer.bg,       desc:"Lidera con el valor de la oferta — funciona bien para audiencias tibias y calientes." },
  { id:"conditions",  label:"Condiciones", emoji:"⏰", color:T.conditions.color,  bg:T.conditions.bg,  desc:"Abre con urgencia o call-out directo — filtra a la audiencia correcta de inmediato." },
];

// ─── FORMATOS DE PRODUCCIÓN DE VIDEO ──────────────────────────────────────────
// Cómo se GRABA el video (no el copy). Se elige UNA vez al inicio para que la IA
// escriba el guion adaptado a ese estilo de producción.
export const VIDEO_PROD_FORMATS: BlockFormat[] = [
  { id:"talking_head",  label:"Cara a cámara (UGC)",          hint:"Una persona habla directo a cámara, estilo selfie/UGC. Lo más fácil de producir y muy creíble." },
  { id:"pov",           label:"POV — perspectiva del avatar", hint:"Cámara subjetiva viviendo el momento del beneficio. 'POV: son las 12:30 y ya sabes dónde almuerzas.'" },
  { id:"before_after",  label:"Antes / Después visual",       hint:"Pantalla dividida o secuencia rápida mostrando el contraste antes→después." },
  { id:"split_screen",  label:"Pantalla dividida",            hint:"Dos clips simultáneos en pantalla partida. Rompe el patrón visual del feed." },
  { id:"asmr_closeup",  label:"Primer plano ASMR / producto", hint:"Primer plano muy cerrado del producto. Genera '¿qué es eso?' y satisfacción visual." },
  { id:"tutorial",      label:"Tutorial / demostración",      hint:"Muestra el paso a paso o el producto en uso. Alta retención, valor primero." },
  { id:"broll_vo",      label:"B-roll + voz en off",          hint:"Tomas del lugar/producto con narración encima. No requiere salir a cámara." },
  { id:"screen_rec",    label:"Grabación de pantalla",        hint:"Captura de la app/web en uso. Ideal para demostrar producto digital." },
  { id:"comment_reply",   label:"Respuesta a comentario",         hint:"Overlay estilo TikTok respondiendo a un comentario (testimonio, objeción u oferta)." },
  { id:"testimonial_cam", label:"Testimonio directo a cámara",    hint:"Cliente real habla a cámara sobre su resultado. Lo más creíble para MOF/BOF. Idealmente con nombre y número." },
  { id:"text_motion",     label:"Solo texto en pantalla",         hint:"Texto animado sin persona en cámara. Rápido de producir, funciona bien con copy de alta especificidad." },
  { id:"interview",       label:"Entrevista / Formato pregunta",  hint:"Alguien hace la pregunta (off-screen o overlay) y el fundador/cliente responde. Estructura natural y alta retención." },
  { id:"whiteboard",      label:"Pizarrón / Diagrama explicativo",hint:"Dibujo o diagrama en tiempo real explicando el mecanismo o proceso. Ideal para mecanismos únicos o procesos técnicos." },
  { id:"skit_drama",      label:"Sketch / Dramatización",         hint:"Actuación que dramatiza el problema (el 'antes') y la solución. Alto engagement, alta identificación del avatar." },
  { id:"unboxing_reveal", label:"Reveal / Unboxing",              hint:"Abrir, revelar o mostrar el resultado por primera vez. Generar anticipación con corte rápido al reveal." },
  { id:"street_interview",label:"Entrevista en la calle",         hint:"Preguntas a personas reales sobre el problema que resuelves. Prueba social orgánica y alta credibilidad." },
  { id:"side_by_side",    label:"Comparación lado a lado",        hint:"Dos escenas simultáneas comparando el método viejo vs. el tuyo, o competidor vs. tu marca." },
  { id:"founder_story",   label:"Historia del fundador",          hint:"El fundador cuenta por qué creó el producto/servicio. Origin story con arco emocional completo." },
  CUSTOM_FORMAT,
];

export const HOOK_TYPE_FORMATS: Record<string, string[]> = {
  pain:       ["pain_curiosity","stakes","confessional","never_again","controversial"],
  promise:    ["promise_curiosity","real_result","cant_believe","kept_for_me","teacher"],
  proof:      ["real_result","analyzer","teacher","cant_believe","journey"],
  curiosity:  ["illegal","kept_for_me","controversial","contrarian","stop_doing"],
  contrarian: ["contrarian","unpopular","controversial","never_again","stop_doing"],
  offer:      ["promise_curiosity","real_result","cant_believe","kept_for_me","illegal"],
  conditions: ["stakes","stop_doing","controversial","never_again","cant_believe"],
};

// ─── PERSONA CONSTANTS ────────────────────────────────────────────────────────
export const AWARENESS_LEVELS: AwarenessLevel[] = [
  { id:"unaware",  label:"Sin conciencia",           short:"Sin coc.",  color:"#64748B", bg:"#F1F5F9", desc:"No saben que tienen un problema" },
  { id:"problem",  label:"Consciente del problema",  short:"Problema",  color:"#D97706", bg:"#FFFBEB", desc:"Conocen el problema, no la solución" },
  { id:"solution", label:"Consciente de la solución",short:"Solución",  color:"#7A5AF6", bg:"#F0EEFE", desc:"Buscando activamente una solución" },
  { id:"product",  label:"Consciente del producto",  short:"Producto",  color:"#2878D4", bg:"#EEF5FF", desc:"Te conocen, evaluando opciones" },
  { id:"most",     label:"Muy consciente",           short:"Listo",     color:"#1A9E6E", bg:"#EDFAF4", desc:"Listo para comprar" },
];

// Género y rango de edad del character builder — "Sin definir" existe a propósito para no
// forzar el foco en género; el usuario siempre puede tipear su propia respuesta libre.
export const PERSONA_GENDER_OPTIONS = [
  { id: "female", label: "Femenino" },
  { id: "male", label: "Masculino" },
  { id: "undefined", label: "Sin definir" },
];
export const PERSONA_AGE_OPTIONS = [
  { id: "18-25", label: "18–25" },
  { id: "25-32", label: "25–32" },
  { id: "32-45", label: "32–45" },
  { id: "45-55", label: "45–55" },
  { id: "60-plus", label: "60+" },
];

// ─── SECCIONES DEL CHARACTER BUILDER DE PERSONAS ───────────────────────────────
// Cada sección es texto libre (para copy/pegar o escribir a mano) con una guía breve de qué
// incluir — pensado para que el texto resultante sea directamente útil como contexto de IA
// al generar copy (por qué: cada categoría ataca una palanca distinta de copywriting directo).
export const PERSONA_SECTIONS = [
  {
    key: "comportamiento",
    emoji: "🎭",
    iconKey: "behavior",
    label: "Comportamiento",
    desc: "Cómo actúa en su día a día y al momento de decidir. Le dice a la IA cómo hablarle y en qué formato.",
    bullets: [
      "Dónde pasa tiempo online (redes, foros, grupos, comunidades)",
      "Cómo consume contenido: video corto, texto largo, podcast, en vivo",
      "Estilo de decisión: impulsivo vs. investiga mucho antes de comprar",
      "Qué la hace actuar YA vs. posponer",
      "Hábitos de compra: compara precios, pide referencias, lee reseñas",
    ],
    placeholder: "Ej. Pasa horas en Instagram y TikTok de noche, prefiere videos cortos con ejemplos reales. Antes de comprar compara 3-4 opciones y busca reseñas. Actúa rápido si ve una oferta con urgencia real, pero desconfía de los descuentos \"todo el año\".",
  },
  {
    key: "background",
    emoji: "🧳",
    iconKey: "background",
    label: "Background",
    desc: "El contexto de vida de esta persona — quién es más allá del problema. Da referencias concretas para sonar específico, no genérico.",
    bullets: [
      "Trabajo o carrera actual, cuánto tiempo lleva en eso",
      "De dónde viene: ciudad, país, tipo de comunidad",
      "Situación familiar / etapa de vida",
      "Nivel socioeconómico aproximado",
      "Rutina diaria típica",
    ],
    placeholder: "Ej. Dueña de una cocina/restaurante familiar hace 6 años en Cochabamba. Casada, dos hijos en primaria. Trabaja 10-12h al día, delega poco porque \"nadie lo hace como ella\". Clase media, reinvierte casi todo en el negocio.",
  },
  {
    key: "likes_dislikes",
    emoji: "💜",
    iconKey: "likesDislikes",
    label: "Likes / Dislikes",
    desc: "Qué le atrae y qué le repele — en marcas, tono de comunicación y en general. Calibra el TONO del copy.",
    bullets: [
      "Marcas o personas que admira (y por qué)",
      "Qué la hace desconfiar de un anuncio (hype, jerga, promesas vacías)",
      "Tipo de humor / lenguaje que conecta con ella",
      "Estética visual que prefiere",
    ],
    placeholder: "Ej. Le gustan las marcas que hablan claro y sin tecnicismos, con ejemplos reales de otros dueños de negocio. Le choca el lenguaje de \"gurú\" y las promesas de \"hazte rico rápido\". Prefiere fotos/videos reales antes que stock genérico.",
  },
  {
    key: "conciencia",
    emoji: "🎯",
    iconKey: "awareness",
    label: "Nivel de consciencia",
    desc: "Según Eugene Schwartz, esto define qué tan directo puede ser tu copy y qué hook usar primero.",
    bullets: [
      "Qué tanto sabe ya sobre el problema",
      "Si ya conoce soluciones parecidas o competidores",
      "Qué le falta saber antes de confiar en una solución",
    ],
    placeholder: "Elaborá acá el porqué del nivel elegido arriba — qué tanto sabe, qué ya probó, qué le falta ver para confiar.",
  },
  {
    key: "dolores",
    emoji: "😣",
    iconKey: "pains",
    label: "Dolores",
    desc: "El dolor real y específico que siente en el día a día — no el problema abstracto. Esto agita tu copy antes de presentar la solución.",
    bullets: [
      "Frases que ella misma usaría para describir el dolor",
      "Momento del día o situación donde el dolor pega más fuerte",
      "Costo del problema si no lo resuelve (tiempo, dinero, relaciones)",
    ],
    placeholder: "Ej. \"Cierro el mes y no sé en qué se fue la plata.\" Le pega más fuerte los domingos en la noche pensando en la semana. Le está costando tiempo con su familia y ya perdió un cliente grande por no responder a tiempo.",
  },
  {
    key: "creencias",
    emoji: "🧠",
    iconKey: "beliefs",
    label: "Creencias",
    desc: "Lo que ella CREE que es cierto sobre su problema o su solución — aunque esté equivocada. Tu copy necesita reconocer o desmontar esta creencia para ganar credibilidad.",
    bullets: [
      "Qué cree que causa su problema",
      "Qué cree que NO va a funcionar (y por qué)",
      "Mitos que ha escuchado y que repite",
    ],
    placeholder: "Ej. Cree que su problema es \"falta de disciplina\" cuando en realidad es falta de un sistema. Cree que automatizar es caro y solo para negocios grandes. Ya escuchó que \"los anuncios no funcionan para negocios pequeños\" y medio le cree.",
  },
];

export const TRAFFIC_TEMPS: TrafficTemp[] = [
  { id:"cold", label:"Frío ❄️",      color:"#3B82F6", bg:"#EFF6FF", border:"#93C5FD" },
  { id:"warm", label:"Tibio 🌤",     color:"#D97706", bg:"#FFFBEB", border:"#FCD34D" },
  { id:"hot",  label:"Caliente 🔥",  color:"#DC2626", bg:"#FEF2F2", border:"#FCA5A5" },
];

export const SUBCOMPONENTS: Record<string, SubcomponentDef[]> = {
  facebook_ad: [
    { id:"hook",        name:"Hook",              def:"Pattern interrupt. First 2-3 lines. Must stop the scroll before 'see more'.", when:"Always first.", example:"Your ads are spending but ROAS won't move — and you have no idea why." },
    { id:"open_loop",   name:"Open Loop",         def:"A question or incomplete idea that creates tension the reader must resolve.", when:"When your avatar is curious but skeptical.", example:"There's one thing top media buyers check before launching any campaign…" },
    { id:"pain_amp",    name:"Pain Amplifier",    def:"Vivid, specific description of the pain. Makes the reader feel seen.", when:"After the hook, when you need emotional connection.", example:"Every morning you open Ads Manager hoping something changed. It hasn't." },
    { id:"agitation",   name:"Agitation",         def:"Escalates the pain. Shows what happens if nothing changes.", when:"After pain amplifier to increase urgency.", example:"At this rate, you'll spend another $3k next month with the same results." },
    { id:"desire",      name:"Desire Statement",  def:"The transformation they want. Identity-level outcome, not features.", when:"After establishing pain, before the solution.", example:"Imagine knowing exactly which ad to scale, which to kill, every single time." },
    { id:"mechanism",   name:"Mechanism Reveal",  def:"The named 'how' — your unique method or insight that makes the solution different.", when:"Introducing your solution. Gives it a memorable name.", example:"We call it the ROAS Triangle — the three levers every profitable campaign shares." },
    { id:"proof",       name:"Proof Block",       def:"Stats, testimonials, case study, or credentials. Backs up the claim.", when:"After desire or mechanism, to build belief.", example:"300+ students. Average 3x ROAS improvement in the first 30 days." },
    { id:"obj_crush",   name:"Objection Crusher", def:"Preemptively handles the #1 reason they'd say no.", when:"Before the CTA, when you know what stops them.", example:"No experience needed — you'll be working with real campaigns from day 1." },
    { id:"future_pace", name:"Future Pace",       def:"Vivid picture of life after the solution. Aspirational and specific.", when:"Before CTA, after proof.", example:"Picture opening Ads Manager on Monday knowing every campaign is dialled in." },
    { id:"social_proof",name:"Social Proof",      def:"Short quote or stat. Borrowed credibility.", when:"Anywhere to reinforce belief.", example:"'Best investment I've made in my business this year.' — Maria, La Paz" },
    { id:"before_after",name:"Before / After",    def:"Contrast state: where they are vs. where they'll be.", when:"Strong visual contrast moment.", example:"Before: $3k/month, 0.8x ROAS. After: $3k/month, 4.2x ROAS." },
    { id:"price_anchor",name:"Price Anchor",      def:"Makes the price feel small vs. the value or vs. alternatives.", when:"Just before the offer or CTA.", example:"One extra qualified call covers the entire cost of the program." },
    { id:"risk_rev",    name:"Risk Reversal",     def:"Guarantee. Removes the fear of being wrong.", when:"Just before CTA, when price is high.", example:"If you don't see improvement in 30 days, we refund everything. No questions." },
    { id:"identity",    name:"Identity Statement",def:"'For people who [identity]…' — makes the avatar self-select.", when:"Hook or opening when targeting a specific persona.", example:"For business owners who are tired of guessing with their ad budget." },
    { id:"cta_fb",      name:"CTA",               def:"Single, specific, frictionless action with a clear reason to act now.", when:"Always last.", example:"Click below and reserve your spot before Friday — 12 left." },
    { id:"headline",    name:"Headline",          def:"40 chars max. The promise in one line. Works completely standalone.", when:"Below the creative image/video.", example:"Master Meta Ads from zero" },
  ],
  video_script: [
    { id:"vid_hook",    name:"Video Hook (0-3s)", def:"Visual + verbal pattern interrupt. Must work without sound. Paired with visual direction and sound suggestion.", when:"Always first 3 seconds.", example:"POV: you just checked Ads Manager and ROAS is 4.2x for the third week straight." },
    { id:"empathy_open",name:"Empathy Open",      def:"'If you're like most [avatar]…' — makes the viewer feel immediately seen.", when:"After hook, to build connection fast.", example:"If you're like most business owners running ads, you're probably guessing more than you'd admit." },
    { id:"story_open",  name:"Story Open",        def:"Specific moment in time. Creates narrative engagement.", when:"When you want a cinematic, personal feel.", example:"6 months ago I was about to shut down my ad account. Today it's our best channel." },
    { id:"prob_walk",   name:"Problem Walkthrough",def:"Step-by-step of the problem. Shows deep understanding of their world.", when:"Middle section, to build credibility.", example:"First you try changing the creative. Doesn't work. Then you try the audience. Still nothing." },
    { id:"turning_pt",  name:"Turning Point",     def:"The moment everything changed. Narrative tension release.", when:"After problem walkthrough.", example:"Then I realised I'd been optimising the wrong metric the whole time." },
    { id:"solution_ts", name:"Solution Tease",    def:"Hints at the solution without revealing all. Keeps watching.", when:"Before the reveal to maintain attention.", example:"And when I found this one thing, my entire approach changed overnight." },
    { id:"benefits_list",name:"List of Benefits", def:"Quick-fire 'You'll get: X, Y, Z' — momentum building, fast.", when:"Mid-video, after solution tease.", example:"You'll know which ad to scale. Which to kill. And exactly when to do it." },
    { id:"comparison_v",name:"Comparison",        def:"Old way vs. new way. Creates clear contrast.", when:"After problem, before solution.", example:"Instead of guessing and hoping — you'll be making decisions from data." },
    { id:"demo",        name:"Demonstration",     def:"Show, don't tell. 'Watch what happens when…'", when:"When you have a tangible thing to show.", example:"[Screen recording of campaign dashboard going from 1.2x to 4.2x ROAS]" },
    { id:"cred_moment", name:"Credibility Moment",def:"Quick credential drop. Establishes authority fast.", when:"Early, before the main pitch.", example:"After managing over $2M in ad spend across 30 accounts, I can tell you…" },
    { id:"testimonial_v",name:"Testimonial Clip", def:"Real customer, specific result. Ideally in their own words.", when:"After your main claim, to back it up.", example:"[Cut to Maria]: 'Within 3 weeks, my ROAS went from 0.9 to 3.4.'" },
    { id:"vid_cta",     name:"CTA (Video)",       def:"Last 5-10 sec. One action only. Repeat it twice.", when:"Always last.", example:"Click the link below. Reserve your spot now. Link is below — don't wait." },
    { id:"sound_sug",   name:"Sound Suggestion",  def:"Trending or mood-matched audio that amplifies the hook's energy.", when:"Specified with the video hook.", example:"Use a confident, punchy beat — something like a trending sound with momentum." },
    { id:"visual_dir",  name:"Visual Direction",  def:"What's on screen: text overlay, b-roll, talking head directions.", when:"Throughout the script.", example:"[Tight crop on face, direct eye contact, good ring light, minimal background]" },
    { id:"mid_interrupt",name:"Mid Pattern Interrupt",def:"Unexpected cut, zoom, or bold statement mid-video to re-engage drifting attention.", when:"Around the 15-20 second mark.", example:"[Zoom in] Wait — I need to show you something." },
    { id:"cliffhanger", name:"Cliffhanger",       def:"Hooks them to stay until the end.", when:"First 5-10 seconds for longer videos.", example:"Stay until the end — I'm going to show you the exact setup we use." },
  ],
};

export const STORAGE_KEY = "copyblocks_beta_v2";

// ─── HOOK FRAMEWORKS ──────────────────────────────────────────────────────────
export const HOOK_FRAMEWORKS: HookFramework[] = [
  { id:"pain_curiosity", cat:"Estructura", label:"Dolor + Curiosidad",
    desc:"Nombra el dolor exacto del avatar y añade un mecanismo nombrado que genera intriga.",
    when:"Cold traffic. Cuando el dolor es claro y urgente.",
    example:"Por qué tus ads gastan pero el ROAS no sube (y el ajuste que lo arregla en 48h)",
    starter:"Por qué [problema exacto] (y cómo [mecanismo] lo resuelve)" },
  { id:"promise_curiosity", cat:"Estructura", label:"Promesa + Curiosidad",
    desc:"Promete un resultado específico ligado a algo contraintuitivo o sorprendente.",
    when:"Cuando tienes resultados concretos que demostrar.",
    example:"Cómo pasé de 0.8x a 4.2x ROAS cambiando solo una métrica que nadie mide",
    starter:"Cómo [resultado específico] haciendo solo [mecanismo inesperado]" },
  { id:"contrarian", cat:"Estructura", label:"Contraintuitivo",
    desc:"Contradice algo que todos dan por sentado. Crea disonancia cognitiva inmediata.",
    when:"Cuando tienes una perspectiva única o datos que van contra la creencia común.",
    example:"Dejar de usar audiencias guardadas fue lo mejor que hice para mis campañas",
    starter:"[Acción que todos hacen] está destruyendo tu [resultado]. Aquí por qué." },
  { id:"stakes", cat:"Estructura", label:"Consecuencias / Stakes",
    desc:"Muestra qué pasa si NO actúan. Incertidumbre sobre el outcome.",
    when:"Para agitar el dolor y crear urgencia real.",
    example:"Cada semana sin arreglar esto = Bs. 500 más que no vuelven",
    starter:"Cada día que [no haces X] = [consecuencia específica que se acumula]" },
  { id:"teacher", cat:"Posicionamiento", label:"Maestro (experto)",
    desc:"Hablas desde experiencia propia. Enseñas algo específico y accionable.",
    when:"Si tienes credenciales, resultados, o experiencia demostrable.",
    example:"Las 3 configuraciones que uso en cada cuenta para mantener ROAS sobre 3x",
    starter:"Las [N] cosas que hago siempre para [resultado]. Las que casi nadie hace." },
  { id:"analyzer", cat:"Posicionamiento", label:"Analizador (no necesitas ser experto)",
    desc:"Estudiaste algo externo y compartes los patrones. Cualquiera puede usarlo.",
    when:"No necesitas experiencia propia — solo analizar y sintetizar.",
    example:"Analicé 50 ads que gastaron +$100k cada uno. Todos tenían estas 3 cosas.",
    starter:"Analicé [N] [cosa externa]. Esto tienen en común los que funcionaron." },
  { id:"journey", cat:"Posicionamiento", label:"Documentando el camino",
    desc:"No eres experto — documentas tu proceso. Garyvee: 'document don't create'.",
    when:"Estás aprendiendo o probando algo. Máxima autenticidad.",
    example:"Día 1 de aprender Meta Ads desde cero — Bs. 200 de presupuesto, cero experiencia",
    starter:"Día [N] de [proceso]. Aquí lo que pasó." },
  { id:"confessional", cat:"Posicionamiento", label:"Confesión (experto + externo)",
    desc:"Experto que admite algo inesperado. Alta credibilidad por la vulnerabilidad.",
    when:"Tienes experiencia y quieres romper la expectativa del lector.",
    example:"Gasté $8,000 en Meta Ads antes de entender por qué nada funcionaba",
    starter:"Gasté [cantidad/tiempo] en [cosa] antes de entender [verdad incómoda]." },
  { id:"cant_believe", cat:"Formato", label:"No puedo creer que encontré esto",
    desc:"Genera FOMO inmediato. El lector quiere saber qué encontraste.",
    when:"Cuando tienes un recurso, hack, o insight que genuinamente sorprende.",
    example:"No puedo creer que esto esté disponible gratis para restaurantes locales",
    starter:"No puedo creer que [descubrimiento valioso] esté [disponible/funcionando así]" },
  { id:"controversial", cat:"Formato", label:"Esto puede ser controversial pero…",
    desc:"Abre un bucle de curiosidad con tensión. Polariza para activar engagement.",
    when:"Tienes una opinión que va contra el consenso del mercado.",
    example:"Esto puede ser controversial: los mejores restaurantes de Cochabamba no necesitan delivery apps",
    starter:"Esto puede ser controversial, pero [verdad que genera fricción en tu mercado]" },
  { id:"never_going_back", cat:"Formato", label:"Por qué nunca volvería a X",
    desc:"Confessional + contraintuitivo. Funciona cuando abandonaste algo que todos hacen.",
    when:"Dejaste una práctica común y encontraste algo mejor.",
    example:"Por qué nunca volvería a abrir mi restaurante sin una lista de clientes propia",
    starter:"Por qué nunca volvería a [práctica común] después de [descubrimiento]" },
  { id:"feels_illegal", cat:"Formato", label:"Esto se siente ilegal de saber",
    desc:"Curiosidad extrema. El lector siente que accede a información privilegiada.",
    when:"Tienes un dato, estrategia, o insight que la mayoría desconoce.",
    example:"Esto se siente ilegal de saber: cómo llenar tu local cualquier día de semana",
    starter:"Esto se siente ilegal de saber: [insight de alto valor que la mayoría no conoce]" },
  { id:"unpopular_opinion", cat:"Formato", label:"Opinión impopular",
    desc:"Toma una postura firme contra algo aceptado. Alta polarización = alto engagement.",
    when:"Tienes una creencia contraria a la norma del mercado que puedes defender.",
    example:"Opinión impopular: la mayoría de negocios locales gasta en ads sin necesitarlo",
    starter:"Opinión impopular: [creencia contraria a lo que tu audiencia acepta como verdad]" },
  { id:"gatekeep", cat:"Formato", label:"Lo iba a guardar para mí pero…",
    desc:"Crea sensación de exclusividad. El lector siente que recibe algo especial.",
    when:"Tienes una estrategia, recurso, o insight que normalmente no compartes.",
    example:"Lo iba a guardar para mí pero: la razón real por la que algunos locales siempre están llenos",
    starter:"Lo iba a guardar para mí, pero [insight, estrategia, o recurso valioso]" },
  { id:"stop_doing", cat:"Formato", label:"Para de hacer X",
    desc:"Directo, imperativo. Interrumpe un comportamiento del avatar.",
    when:"Tu avatar está haciendo algo contraproducente que puedes identificar claramente.",
    example:"Para de pagar por delivery apps si no tienes lista de clientes propia primero",
    starter:"Para de [comportamiento común y contraproducente] antes de [condición previa]" },
  { id:"proof_of_work", cat:"Formato", label:"Resultado específico de alguien real",
    desc:"Especificidad máxima: persona + resultado + tiempo. La más creíble.",
    when:"Tienes un caso real — tuyo o de un cliente — con números verificables.",
    example:"Cómo Don Beto pasó de 3 a 47 domicilios diarios cambiando una sola cosa",
    starter:"Cómo [persona específica] logró [resultado con número] en [tiempo] con [mecanismo]" },
  { id:"enthusiasm", cat:"Emoción", label:"Entusiasmo personal",
    desc:"Energía genuina sobre un producto o resultado. Contagia la emoción al espectador.",
    when:"Tienes un resultado real o producto que usas — la autenticidad es clave.",
    example:"Acabo de implementar esto en mi restaurante y estoy súper emocionado",
    starter:"Acabo de [descubrir/conseguir/implementar] [X] y estoy emocionado/a" },
  { id:"myth_reveal", cat:"Emoción", label:"Mito revelado",
    desc:"Expone 3-4 creencias falsas que tiene el avatar sobre su problema o solución.",
    when:"Tu avatar tiene misconceptions que lo frenan — destruirlas genera confianza.",
    example:"3 mitos sobre Meta Ads que están destruyendo el ROAS de restaurantes locales",
    starter:"[N] mitos sobre [X] que te están costando [consecuencia]" },
  { id:"frustration", cat:"Emoción", label:"Frustración / Problema cotidiano",
    desc:"Nombra directamente una frustración recurrente del avatar. 'Por fin alguien lo dice.'",
    when:"El avatar vive algo molesto a diario — lo escucha y se siente comprendido.",
    example:"Llevar la contabilidad del restaurante es un problema constante y nadie lo resuelve bien",
    starter:"[Situación frustrante del avatar] es una lucha constante" },
  { id:"obsession", cat:"Emoción", label:"Obsesión / Adicción positiva",
    desc:"Cuenta algo que no puedes dejar de usar o hacer. Genera FOMO y curiosidad.",
    when:"Tienes experiencia real con el producto — la primera persona funciona bien.",
    example:"Estoy completamente obsesionado con esta forma de conseguir domicilios sin apps",
    starter:"Estoy completamente obsesionado/a con [X] — y por eso" },
  { id:"age_identity", cat:"Prueba social", label:"Identidad por edad / grupo",
    desc:"Habla desde una identidad específica: edad, profesión, situación. Crea identificación inmediata.",
    when:"Tu avatar se identifica fuertemente con una categoría (edad, rol, situación).",
    example:"Tengo 42 años y soy dueño de restaurante. Así es cómo [X] cambió mis números este año.",
    starter:"Tengo [edad/rol]. Así es cómo [X] me ayudó con [problema específico]" },
  { id:"honest_review", cat:"Prueba social", label:"Opinión honesta",
    desc:"Review personal franca. 'Te cuento la verdad, no lo que quieres escuchar.' Alta credibilidad.",
    when:"Tienes experiencia real con algo que el avatar está evaluando comprar o hacer.",
    example:"Mi opinión honesta sobre las apps de delivery después de 8 meses usándolas",
    starter:"Mi opinión honesta sobre [X] después de [tiempo/experiencia]" },
  { id:"tutorial_steps", cat:"Paso a paso",
    label:"X pasos para [resultado]",
    desc:"Enuncia el resultado, muestra el número de pasos, implica la simplicidad del proceso.",
    when:"Tienes un proceso claro que puedes simplificar en pasos contables.",
    example:"3 pasos para conseguir domicilios propios sin pagar comisión a ninguna app",
    starter:"[N] pasos para [resultado específico con número]" },
  { id:"authority_steal", cat:"Autoridad",
    label:"Roba mi estrategia exacta",
    desc:"Reclama resultados, ofrece el proceso exacto. Alta credibilidad por la especificidad.",
    when:"Tienes un proceso probado con resultados reales que puedes mostrar.",
    example:"Roba mi estrategia exacta para duplicar pedidos sin bajar precios — la que usé con 12 restaurantes este año",
    starter:"Roba mi estrategia exacta para [resultado]. Aquí está:" },
  { id:"before_after", cat:"Transformación",
    label:"De [malo] a [bueno] en [tiempo]",
    desc:"Contraste máximo en mínimas palabras. El tiempo le da credibilidad — específico siempre.",
    when:"Tienes una transformación real con antes/después y tiempo específico.",
    example:"De Bs. 200 a Bs. 2.800 en domicilios por mes. En 47 días.",
    starter:"De [situación pasada] a [resultado con número] en [tiempo exacto]." },
  { id:"direct_question", cat:"Pregunta directa",
    label:"¿Alguna vez has [frustración relatable]?",
    desc:"Crea reconocimiento inmediato. El avatar siente que le leen la mente.",
    when:"Conoces una frustración muy específica que tu avatar vive regularmente.",
    example:"¿Alguna vez checaste las estadísticas de tu anuncio y no entendiste qué significaban?",
    starter:"¿Alguna vez [frustrante situación cotidiana de tu avatar]? Aquí está la razón real:" },
  { id:"comparison_gap", cat:"Comparación",
    label:"La diferencia entre promedio y excepcional",
    desc:"El gap crea intriga. Convierte al lector en alguien que quiere estar en el 1%.",
    when:"Puedes identificar la variable que separa resultados mediocres de excepcionales.",
    example:"La diferencia entre un restaurante con 30 domicilios al mes y uno con 300 es una sola cosa. Aquí está.",
    starter:"La diferencia entre [resultado promedio] y [resultado excepcional] es una sola cosa:" },
  { id:"trend_change", cat:"Tendencia",
    label:"[X] está cambiando en [año]",
    desc:"Los algoritmos aman el contenido en tiempo real. El FOMO impulsa el engagement.",
    when:"Hay un cambio real en tu industria que afecta directamente a tu avatar ahora.",
    example:"Meta Ads está cambiando en 2026 — y si no ajustas esto, tus campañas van a costar el doble",
    starter:"[Plataforma/industria] está cambiando en [año] — aquí lo que significa para [avatar]:" },
  { id:"fear_costing", cat:"Advertencia",
    label:"Este error te está costando [X]",
    desc:"Amenaza específica con costo cuantificable. Más efectivo cuando el error es no obvio.",
    when:"Puedes identificar un error específico y no obvio que tiene un costo cuantificable.",
    example:"Este simple ajuste (que el 94% omite) podría estar costándote Bs. 500 en comisiones cada semana",
    starter:"Este [error específico] podría estar costándote [pérdida cuantificable]. Aquí está la prueba:" },
];

// ─── ÁNGULOS (Modo rápido / nodo Ángulo del Compositor) ───────────────────────
// Cada ángulo recomienda los formatos de producción y las fórmulas de hook que mejor le calzan.
// prods = ids de VIDEO_PROD_FORMATS · hooks = ids de HOOK_FRAMEWORKS (en orden de relevancia).
export const ANGULOS_RAPIDO = [
  { id:"dolor",      emoji:"💔", iconKey:"directPain", label:"Dolor directo (PAS)",        desc:"Hook de dolor → agitar el problema → solución. Para tráfico frío que ya siente el problema.",
    prods:["talking_head","skit_drama","pov","before_after","text_motion","broll_vo"],
    hooks:["pain_curiosity","frustration","direct_question","fear_costing","myth_reveal","stakes"] },
  { id:"contrarian", emoji:"⚡", iconKey:"counterintuitive", label:"Contraintuitivo",             desc:"Rompe una creencia que todos dan por sentada. Genera disonancia cognitiva que detiene el scroll.",
    prods:["talking_head","whiteboard","text_motion","side_by_side","interview","broll_vo"],
    hooks:["contrarian","unpopular_opinion","controversial","myth_reveal","stop_doing","never_going_back"] },
  { id:"prueba",     emoji:"⭐", iconKey:"socialProof", label:"Prueba social lidera",        desc:"Hook con resultado de cliente real. Alta credibilidad inmediata. Ideal para tráfico tibio/MOF.",
    prods:["testimonial_cam","street_interview","comment_reply","before_after","interview","talking_head"],
    hooks:["proof_of_work","before_after","honest_review","age_identity","comparison_gap","journey"] },
  { id:"curiosidad", emoji:"🔮", iconKey:"mechanismCuriosity", label:"Mecanismo + Curiosidad",      desc:"Insinúa el cómo. Crea un bucle abierto que necesitan cerrar antes de seguir scrolleando.",
    prods:["whiteboard","tutorial","screen_rec","talking_head","text_motion","asmr_closeup"],
    hooks:["promise_curiosity","feels_illegal","gatekeep","cant_believe","comparison_gap","teacher"] },
  { id:"oferta",     emoji:"🎁", iconKey:null, label:"Oferta directa",              desc:"Stack de valor + ancla de precio + CTA. Para retargeting/BOF cuando ya saben que existís.",
    prods:["talking_head","unboxing_reveal","asmr_closeup","text_motion","comment_reply","before_after"],
    hooks:["promise_curiosity","proof_of_work","cant_believe","gatekeep","authority_steal","tutorial_steps"] },
  { id:"confesion",  emoji:"🎭", iconKey:"confession", label:"Confesión / Nunca volvería",  desc:"Admitir algo inesperado. Hook de alta credibilidad por vulnerabilidad. Funcionan muy bien en video.",
    prods:["talking_head","founder_story","testimonial_cam","interview","pov","broll_vo"],
    hooks:["confessional","never_going_back","honest_review","enthusiasm","journey","obsession"] },
  { id:"stakes",     emoji:"🔥", iconKey:"stakes", label:"Consecuencias (Stakes)",      desc:"Lo que le cuesta NO actuar. Urgencia por costo de inacción acumulado, con números específicos.",
    prods:["talking_head","skit_drama","text_motion","before_after","side_by_side","broll_vo"],
    hooks:["stakes","fear_costing","trend_change","stop_doing","myth_reveal","direct_question"] },
];

// Tipo de bloque con el que arranca cada ángulo (para clasificar el Hook al guardarlo en el banco).
export const ANGULO_HOOK_TIPO: Record<string,string> = { dolor:"pain", contrarian:"curiosity", prueba:"proof", curiosidad:"curiosity", oferta:"offer", confesion:"proof", stakes:"conditions" };

// ─── AVATARES DE PERSONA (picker "estilo Sims" del nodo Persona) ──────────────
export const PERSONA_EMOJIS = [
  "🧑‍💼","👩‍💼","👨‍🍳","👩‍🍳","🧑‍🎨","👩‍⚕️","👨‍🔬","🧑‍🚀","👩‍🏫","👨‍💻","🧑‍🎤","👵","👴","🧕","👨‍🌾",
];

// ─── TIPOS DE BLOQUE ─────────────────────────────────────────────────────────
export const TIPOS_BLOQUE: TipoBloque[] = [
  { id:"pain",       label:"Dolor",       color:"#D94F4F", bg:"#FFF2F2", border:"#F5BCBC",
    def:"El lugar donde está tu avatar ahora. Dolor vivido, específico, cotidiano.",
    subtypes:["Pain cotidiano","Pain de identidad","Pain de recursos (tiempo/dinero)","Pain de experiencia pasada","Pain de creencias bloqueantes"],
    tip:"Cuanto más específico y visual sea el dolor, más se sentirá identificado. Evita 'quiero crecer' — di exactamente qué no está funcionando." },
  { id:"promise",    label:"Promesa",     color:"#1A9E6E", bg:"#EDFAF4", border:"#9EE0C6",
    def:"Adónde quiere llegar tu avatar. La tierra prometida. Siempre con número o resultado concreto.",
    subtypes:["Resultado concreto (número)","Transformación de identidad","Beneficio emocional","Beneficio práctico","Libertad / autonomía"],
    tip:"Una buena promesa tiene número + tiempo + sin X obstáculo. Ej: 3x más domicilios en 30 días sin bajar precios." },
  { id:"proof",      label:"Prueba",      color:"#2878D4", bg:"#EEF5FF", border:"#A8CCFA",
    def:"El piloto que da credibilidad. Resultado real de alguien específico > número de clientes > rating.",
    subtypes:["Testimonio con resultado específico","Número de clientes/casos","Credencial del fundador","Dato externo verificable","Demostración visual"],
    tip:"Orden de efectividad: resultado específico (nombre+número) > cantidad de usuarios > autoridad externa > estrellas sin contexto." },
  { id:"curiosity",  label:"Curiosidad",  color:"#7A5AF6", bg:"#F0EEFE", border:"#BDC0EF",
    def:"El mecanismo nombrado — el helicóptero que lleva del Pain al Promise. Debe ser nuevo y único.",
    subtypes:["Mecanismo nombrado (Named Mechanism)","Insight contraintuitivo","Proceso único","Framework propio","Dato que cambia perspectiva"],
    tip:"El mecanismo necesita un nombre. 'El Triángulo ROAS'. 'El Método 3-30'. Un nombre hace que sea memorable y percibido como exclusivo." },
  { id:"constraints",label:"Frenos",      color:"#C07C10", bg:"#FFF8EA", border:"#F0D080",
    def:"Todo lo que frena a tu avatar de actuar. Más profundo que las objeciones — incluye identidad y creencias.",
    subtypes:["Constraints de identidad ('yo no soy el tipo de persona que...')","Constraints de valores","Constraints de creencias (maleables)","Constraints de recursos (tiempo/dinero/energía)","Constraints de experiencias pasadas"],
    tip:"Identidad y valores son casi imposibles de cambiar — trabájalos alrededor. Creencias son maleables — usa proof y reframing. Recursos — muestra que es más rápido/barato que la alternativa." },
  { id:"conditions",  label:"Condiciones", color:"#C44F82", bg:"#FEF0F5", border:"#F0B4D0",
    def:"La dinamita con cuenta regresiva. Urgencia, escasez, y el call-out de audiencia específica.",
    subtypes:["Urgencia temporal (fecha real)","Escasez real (plazas/stock)","Call-out de avatar específico ('si tienes un restaurante...')","Condición de elegibilidad","Bonus temporal"],
    tip:"Urgencia FALSA destruye la confianza a largo plazo. Solo usa condiciones reales y verificables. El call-out de avatar es el más subutilizado y más efectivo." },
];

// ─── DEMO BRAND ───────────────────────────────────────────────────────────────
export const DEMO_BRAND: Brand = {
  id:"roas1", name:"ROAS Academy", industry:"Educación online / Marketing digital",
  perfil:{
    produto:"Academia online que forma media buyers desde cero: cursos en video, plantillas, comunidad y mentoría en vivo para aprender a manejar Meta Ads de forma profesional.",
    oferta:"Programa de 8 semanas: fundamentos de Meta Ads, estructura de cuentas, copy y creativos, escalado de presupuesto y mentoría semanal en vivo con acceso a la comunidad de por vida.",
    diferenciador:"No es teoría de curso grabado y listo: cada alumno maneja una cuenta real con presupuesto real durante el programa, con feedback semanal 1 a 1 de un mentor que sigue manejando cuentas hoy.",
    voz:"Directo y sin relleno motivacional vacío. Habla como un media buyer con experiencia real, no como un gurú. Cercano, con ejemplos concretos y números reales. Habla de TÚ al alumno.",
    mercado:"LATAM — personas que quieren vivir del marketing digital (freelance o en agencia). Español neutro.",
    ubicacion:"Remoto — equipo y alumnos distribuidos en toda LATAM.",
    mecanismo_nombrado:"Método Cuenta Real",
    mecanismo_descripcion:"Cada alumno gestiona una cuenta publicitaria real con presupuesto real desde la semana 2, en vez de solo ver clases — así el aprendizaje queda grabado en la práctica, no en la teoría.",
    mecanismo_diferenciador:"La mayoría de cursos de marketing son videos grabados sin práctica real. Acá cada alumno toma decisiones reales de presupuesto con un mentor revisando sus resultados cada semana.",
    mecanismo_creencia_rebate:"La gente cree que necesita años de experiencia para manejar presupuesto real. Con mentoría semanal desde el día uno, esa curva se acorta a semanas.",
    prueba_n_clientes:"+1.200 alumnos formados desde 2021",
    prueba_caso:"Camila (Perú): empezó sin experiencia y a los 4 meses de terminar el programa ya manejaba $8.000/mes en presupuesto para 3 clientes propios.",
    prueba_resultado_clave:"68% de los alumnos consigue su primer cliente o empleo en marketing dentro de los 90 días de terminar",
    prueba_autoridad:"Mentores activos manejando cuentas reales hoy, no solo instructores de video",
    prueba_cuota_mercado:"",
    extra:"Precio del programa: 3 cuotas. Cupos limitados por cohorte para mantener la mentoría 1 a 1. Próxima cohorte cada 2 meses."
  },
  avatars:[
    { id:"av1", nombre:"Camila — quiere cambiar de carrera", edad:"25-32", rol:"Trabaja en un rubro que no le gusta y quiere vivir del marketing digital",
      descripcion:"Vio contenido de marketing en redes durante meses pero nunca dio el salto porque siente que le falta la base técnica real.",
      problema_principal:"No sabe por dónde empezar y le da miedo invertir en un curso más que se quede en la teoría.",
      antes:"Trabajo de oficina que no le gusta, mirando tutoriales gratis de YouTube sin un camino claro.",
      dolores:"Sensación de estar perdiendo el tiempo, no saber si realmente puede vivir de esto, miedo a gastar dinero en otro curso que no sirva.",
      intentos_fallidos:"Compró 2 cursos grabados baratos que nunca terminó porque no tenían seguimiento ni cuenta real donde practicar.",
      creencia_falsa:"Cree que necesita años de experiencia en una agencia antes de poder manejar clientes propios.",
      deseo_final:"Poder decir 'vivo del marketing digital' y manejar sus propios clientes o conseguir un trabajo remoto bien pago.",
      objeciones:"¿Y si no tengo tiempo para dedicarle? ¿Esto realmente funciona o es como los otros cursos que compré?",
      lenguaje:"'quiero cambiar de rubro', 'no sé si esto es para mí', 'ya gasté plata en cursos que no sirvieron'",
      nivel_conciencia:"problem" },
    { id:"av2", nombre:"Rodrigo — freelancer quiere escalar", edad:"27-35", rol:"Ya hace algo de marketing freelance pero de forma desordenada",
      descripcion:"Tiene 1-2 clientes propios pero aprendió todo probando y mirando videos sueltos — sabe que le faltan bases sólidas.",
      problema_principal:"No tiene un método consistente y le cuesta justificar resultados o subir sus tarifas frente a los clientes.",
      antes:"Maneja cuentas chicas a prueba y error, sin un proceso claro de estructura ni de escalado.",
      dolores:"Resultados inconsistentes entre clientes, no saber explicar por qué algo funcionó o no, techo bajo de tarifas.",
      intentos_fallidos:"Miró decenas de videos gratis en YouTube pero le falta la estructura y el feedback de alguien con más experiencia.",
      creencia_falsa:"Cree que ya sabe lo suficiente y que un curso formal no le va a aportar nada nuevo.",
      deseo_final:"Tener un método probado y confianza real para subir tarifas y conseguir clientes más grandes.",
      objeciones:"¿Voy a aprender algo que ya no sepa? ¿Vale la pena el precio si ya tengo clientes?",
      lenguaje:"'ya tengo clientes pero siento que voy a ciegas', 'quiero subir mis tarifas', 'necesito un método real'",
      nivel_conciencia:"solution" },
  ],
  competitors:[
    { id:"comp1", name:"Cursos grabados genéricos", url:"", notes:"Baratos y accesibles. Desventaja: sin mentoría ni cuenta real, alto abandono, el alumno queda con teoría pero sin práctica real." },
    { id:"comp2", name:"Aprender solo con contenido gratis (YouTube/redes)", url:"", notes:"Gratis. Desventaja: sin estructura ni orden, sin feedback personalizado, resultados muy lentos e inconsistentes." },
  ],
  assets:[
    { id:"a1", tipo:"pain", funcs:["hook"], tags:["hook","concepto:c1"],
      text:"Comprás otro curso, ves los primeros 3 videos con muchas ganas... y ahí se queda. Otra vez." },
    { id:"a2", tipo:"pain", funcs:["body"], tags:["body","concepto:c1"],
      text:"Miraste horas de tutoriales gratis, compraste algún curso barato, y seguís sin manejar ni un solo cliente real. La teoría la tenés. La práctica, no." },
    { id:"a3", tipo:"promise", funcs:["body"], tags:["body","concepto:c1"],
      text:"Desde la semana 2 manejás una cuenta real con presupuesto real, con un mentor revisando tus decisiones cada semana. Aprendés haciendo, no mirando." },
    { id:"a4", tipo:"proof", funcs:["body"], tags:["body","concepto:c1"],
      text:"Camila empezó sin experiencia. A los 4 meses de terminar el programa ya manejaba $8.000/mes en presupuesto para 3 clientes propios." },
    { id:"a5", tipo:"conditions", funcs:["cta"], tags:["cta","concepto:c1"],
      text:"Cupos limitados por cohorte para poder darte mentoría 1 a 1. Postulá a la próxima cohorte hoy." },
  ],
  conceptos:[
    { id:"c1", concepto:"La gente compra curso tras curso de marketing pero nunca da el salto a manejar un cliente real por falta de práctica y seguimiento", angulo:"pain_curiosity", estilo:"ugc", hook:"Comprás otro curso, ves los primeros 3 videos con muchas ganas... y ahí se queda. Otra vez." },
  ],
  customAngles:[], customStyles:[],
  copies:[],
  offers:[
    { id:"of1", nombre:"Programa ROAS Academy — 8 semanas", descripcion:"Fundamentos de Meta Ads + estructura de cuentas + copy y creativos + escalado de presupuesto, con mentoría semanal en vivo y una cuenta real desde la semana 2.",
      precio:"3 cuotas", urgencia:"Cupos limitados por cohorte para mantener la mentoría 1 a 1", garantia:"Acceso de por vida a la comunidad y a las próximas actualizaciones del programa.",
      incluye:"8 semanas de programa, mentoría semanal en vivo, cuenta real con presupuesto real, comunidad de por vida.",
      resultado:"Manejar presupuesto real con confianza y conseguir el primer cliente o empleo en marketing", tiempo:"8 semanas + 90 días de acompañamiento post-programa",
      antes:"Mirando tutoriales sueltos sin método ni cuenta real donde practicar", despues:"Manejando una cuenta real con un método claro y mentoría semanal",
      precio_ancla:"Costo de contratar un mentor privado por 8 semanas", friccion_eliminada:"Pago en 3 cuotas, cupos limitados garantizan atención personalizada" },
  ],
};

// ─── AI PROVIDERS ─────────────────────────────────────────────────────────────
export const AI_PROVIDERS: AIProviderConfig[] = [
  {
    id: "anthropic",
    name: "Claude",
    logo: "✦",
    color: "#D97706",
    bg: "#FFFBEB",
    border: "#FCD34D",
    placeholder: "sk-ant-api03-...",
    hint: "console.anthropic.com",
    hintUrl: "https://console.anthropic.com",
    validate: (k: string) => k.length > 10 || "Ingresa una API key válida",
    model: "claude-sonnet-4-5",
  },
  {
    id: "openai",
    name: "ChatGPT / OpenAI",
    logo: "⬡",
    color: "#10A37F",
    bg: "#F0FDF9",
    border: "#6EE7B7",
    placeholder: "sk-proj-...",
    hint: "platform.openai.com/api-keys",
    hintUrl: "https://platform.openai.com/api-keys",
    validate: (k: string) => k.length > 10 || "Ingresa una API key válida",
    model: "gpt-4o",
  },
  {
    id: "gemini",
    name: "Gemini",
    logo: "✦",
    color: "#4285F4",
    bg: "#EFF6FF",
    border: "#93C5FD",
    placeholder: "AIzaSy...",
    hint: "aistudio.google.com/app/apikey — tier gratuito disponible",
    hintUrl: "https://aistudio.google.com/app/apikey",
    validate: (k: string) => k.length > 10 || "Ingresa una API key válida",
    model: "gemini-1.5-pro",
  },
];
